### PR TITLE
Update to Compose 1.0.0-beta01

### PR DESCRIPTION
**Pull request by amatsegor**

### CODE REVIEW

**Comment by amatsegor** [comment]
Hi @zsoltk !
Could you please update a Java version to 11 on your CI?
Gradle plugin requires Java 11 since 7.0.0-alpha01 version, so compilation fails now

**Comment by zsoltk** [comment]
Hi @amatsegor! I started the migration myself, you were quicker :) Many thanks! Let me look into it.

**Comment by abd3lraouf** [comment]
@amatsegor Hey you can just continue with this as the contents of `.github/workflows/gradle.yml` file

```yml
name: Build
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

jobs:
  validation:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
  gradle:
    name: Build Gradle Tasks
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11    
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cache Gradle Caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-gradle-cache
      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-gradle-wrapper
      - name: Run Gradle tasks
        run: ./gradlew build --continue
      - name: Stop Gradle
        run: ./gradlew --stop
```

**Comment by amatsegor** [comment]
@AbdElraoufSabri it worked, thanks a lot! Checks are passed now

**Comment by abd3lraouf** [comment]
@amatsegor Never mind that's what we are here for. So may anyone merge it?

**Comment by zsoltk** [comment]
Thank you all! Will create new release soon.

**Pull request merged**
