### PR TITLE
Alpha04

### PR DESCRIPTION
**Pull request by madhavajay**
Updating to Alpha04

### CODE REVIEW

**Comment by zsoltk** [comment]
Hey @madhavajay , just curious, why did you redo everything since alpha01 instead of basing your PR on top of current master (alpha03)?

**Comment by zsoltk** [comment]
Your commit history is confusing. To resolve it, I cherry-picked your relevant commit (so it's still your contribution) and pushed it cleanly in #44.

**Comment by madhavajay** [comment]
Hi @zsoltk oh sorry, something weird is happening, i think its because my forks master isn't up to date? Super annoying. Why is this not a button in GitHub to just sync?

I have been fetching your master and then branching and pushing to my fork and creating the PR but i guess it has no history on my master so it needs to include the whole history?

I'm also surprised GitHub doesn't figure this out automatically, anyway sorry about this, I will pay closer attention next time.

**Comment by zsoltk** [comment]
No prob :) 

Suggestion: always confirm your branching history visually in CI / some tool before pushing, it's not in GitHub's scope to change that. If something's messed up, you might want to rebase things.

**Pull request closed without merging**
